### ISSUE TITLE
Hogwarts Legacy

### ISSUE THREAD

**Issue by Dastano** [gitMenv/UEcastoc#10]
Hey, would you mind checking out Hogwarts Legacy? It uses a mix between pak and ucas Files. But sadly your tool cant open the files atm.

panic: runtime error: index out of range [3] with length 3
main.main()
        C:/Users/Menno/Desktop/Modding/UEcastoc/packProgram/main.go:120 +0x449

**Comment by Dastano** [comment]
https://mega.nz/file/mYoWUD6B#me2o11pnUPWmGr5loHqfAQbhCHmFWBBh-atvUzPz8h0

**Comment by gitMenv** [comment]
You're quite early with Hogwarts Legacy! The files that you sent are only the global.utoc and .ucas files. These files do not contain the actual game data; those should be in the larger .utoc, .ucas and .pak files. I do assume that the game data is encrypted, but based on this I can not see if that's the case.

**Comment by Dastano** [comment]
Hey there,

well, it's early access. I uploaded the file as an example.  Since other files are bigger. 

You can grab the Full Client at https://cs.rin.ru/forum/viewtopic.php?f=10&t=93177&hilit=hogwarts&start=60 if you like.


I just got the Error I showed you, thats why I opened the issue, I guess once that is solved, we can open all the Game Files. Its also funny, they use a mix from ucas and pak Files.


Pak files can be extracted fine with no issue, with any other tools, just ucas files are an issue.

**Comment by Cyberim** [comment]
There is another problem. You cannot view and modify the uasset file. The tool does not support it

**Comment by Dastano** [comment]
Yeah, I heard that, that uassets using a different format, that's fine too, I am more interested in Map Data other useful stuff.

Maybe the Uasset Guy also updates his Tool now, if that is even possible. It seems ucas is way different from normal stuff.

**Comment by Dastano** [comment]
Can you open the ucas I sent you tho? Maybe you can push the fix?

**Comment by gitMenv** [comment]
With the DLL and the new main.exe program in the cpp folder, I believe it should be possible to create a mod for Hogwarts Legacy.
