### ISSUE TITLE
Hogwarts Legacy file format .uptnl

### ISSUE THREAD

**Issue by christiancoleman** [gitMenv/UEcastoc#13]
Hey there, trying to use this with Hogwarts Legacy and after some finagling I was able to extract the assets, but (and I'm new to Unreal Engine 4 modding so forgive me if this is obvious/basic) but the files are in a .uptnl format. What is that exactly? How can I use these? I'm wondering if I need to provide an AES key maybe?

**Comment by narknon** [comment]
Those are specific files for certain types of optional bulk data (e.g., for textures).  There should be other uasset files as well in other paks.
