### ISSUE TITLE
Go fails to compile project

### ISSUE THREAD

**Issue by BreakfastBrainz2** [gitMenv/UEcastoc#25]
When trying to compile a fresh git clone of the master branch with Go, it fails and gives the following error log:
D:\uecastoctoolsrc\UEcastoc>go build -o castoc_x64.dll -buildmode=c-shared -ldflags "-s -w" .
# github.com/gitMenv/UEcastoc
.\pack.go:92:37: undefined: sha1Hash
.\pack.go:116:46: undefined: getRandomBytes
.\pack.go:135:19: undefined: stringToFString
.\pack.go:139:13: undefined: uint32ToBytes
.\pack.go:145:13: undefined: uint32ToBytes
.\pack.go:151:13: undefined: uint32ToBytes
.\pack.go:153:13: undefined: stringToFString
.\pack.go:349:16: undefined: sha1Hash
.\pack.go:389:45: undefined: getRandomBytes
.\pack.go:406:21: undefined: encryptAES
.\pack.go:406:21: too many errors

**Comment by gitMenv** [comment]
These errors mean that you are missing the dependencies. These should be installed using the `go get <packagename>` command.
All dependencies of this project are listed in the go.mod file, so Go already knows where to look and they should be installed upon build. It may be a problem with the GOPATH variable on your system, but it's not an issue with this project.
Try to find a way to tell Go where the modfile is. Maybe `go get github.com/gitMenv/UEcastoc`?
