### ISSUE TITLE
 error occurs 

### ISSUE THREAD

**Issue by Real-n3tron** [gitMenv/UEcastoc#9]
Showing this error when unpacking a .ucas file
![error](https://user-images.githubusercontent.com/85865716/217174295-927651b7-d686-4fc1-bf46-d3692e5d991b.png)

**Comment by gitMenv** [comment]
The unpacker is currently able to parse and unpack the game files from Grounded. If it does unpack other .ucas/.utoc files, that is great! In this case, it apparently doesn't.
I am working on a solution to this, extending the "unpacking support" for more utoc file types. This will be a DLL that can be used with any C-like programming language, but it will take a little bit more time. In the meantime, could you attach the packchunk0-Android_ETC2.ucas and .utoc files somehow? Then I can try to make it work with those files as well

**Comment by Real-n3tron** [comment]
[](https://drive.google.com/drive/folders/13r72tWZS8VZZs9Cl8Qe0do4exDf6Q1mS)  I added a drive link where u will find the ucas and utoc files . Also I provided the aes key in two formats

**Comment by Real-n3tron** [comment]
If it will works for my game pls notify me

**Comment by gitMenv** [comment]
> If it will works for my game pls notify me

I have found the differences between the Grounded game files and the files that you sent. I also implemented the decryption to actually use the AES decryption. I have done major reworks to the code and it's entirely different now, so I will have to restructure a few things before I can push it. In the meantime, I was able to unpack the game files from the .ucas/.utoc files that you sent, which I'll post here:
link:- https://drive.google.com/file/d/1A_nnXRoxB9xkfyGuCidsxDLnyGSmcs0l/view?usp=sharing
Maybe you can do something with it :)

**Comment by Real-n3tron** [comment]
Yeah I've made changes to some of the uassets file. I need to repack them . So, without ur programme I can't do that.
